### ISSUE TITLE
Missing dependency 'trollius' in NeoVim

### ISSUE THREAD

**Issue by ns-cweber** [reasonml/vim-reason#4]
When I install this plugin in NeoVim, I get the following error:

```py
"src/main.re" [noeol] 65L, 1974C
function provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/__init__.py", line 8, in <module>
    from .event_loop import EventLoop
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/event_loop/__init__.py", line 12, in <module>
    from .asyncio import AsyncioEventLoop
  File "/Users/cweber/Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/event_loop/asyncio.py", line 22, in <module>
    import trollius as asyncio
ImportError: No module named trollius
```

It's probably user error of some sort, but if this is the case, the docs could be updated to make it clearer?

**Comment by chenglou** [comment]
I don't have this error... weird

Sorry, I'm not a full-time vim user. I've installed nvim through brew. Maybe some more knowledgeable people know the fix?

**Comment by bassjacob** [comment]
This looks like it could be an error with neovim's msgpack_rpc package. @ns-cweber have you followed the neovim instructions for setting it up for remote plugins?

If you run
```
pip install --upgrade neovim
pip3 install --upgrade neovim
nvim +UpdateRemotePlugins +qall
```

does the error still occur?

**Comment by ns-cweber** [comment]
@bassjacob This seems to fix the problem (or at least I don't see it any more), but now I'm seeing:

```
"src/main.re" 30L, 645C
Error detected while processing function 80[16]..88:
line    8:
E605: Exception not caught: Syntastic: Duplicate syntax checker name: reason/merlin
Press ENTER or type command to continue
Error detected while processing function <SNR>38_VimEnterHook[7]..<SNR>38_UpdateErrors[15]..<
SNR>38_CacheErrors[20]..81:
line   30:
E170: Missing :endfor
Press ENTER or type command to continue
Error detected while processing function <SNR>38_VimEnterHook[7]..<SNR>38_UpdateErrors[15]..<
SNR>38_CacheErrors:
line   20:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>38_VimEnterHook[7]..<SNR>38_UpdateErrors:
line   15:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>38_VimEnterHook:
line    7:
E171: Missing :endif
Press ENTER or type command to continue
```

If I disable syntastic, this goes away, so this is probably a different issue. I'll leave it up to you as to whether you want to close this issue.

**Comment by bassjacob** [comment]
Okay, this is good progress. Can you now try deleting and reinstalling all
your plugins? And then running `:UpdateRemotePlugins` again?

**Comment by bassjacob** [comment]
@ns-cweber is this still an issue for you?

**Comment by ns-cweber** [comment]
@bassjacob Nope.

**Comment by seanw2020** [comment]
For anybody else reading this, _Plugin 'jaxbot/github-issues.vim'_, which hasn't been updated in the last two years, caused this same behavior--at least on my system using Vundle. When I removed it, the problem disappeared. It took me about 6 hours to figure that out, so maybe that will save you time and frustration.
